### ISSUE TITLE
Feature suggestion : Include "Surface" elements

### ISSUE THREAD

**Issue by guillaumecardon** [Sadret/openrct2-scenery-manager#19]
It could be interesting to have an option to include "surface" element when you want copy paste a selection area.

This feature would be great, for example if you made a giant mountain, with differents heights / corners on each square, and copy paste it on another place in a map.

**Comment by Sadret** [comment]
I thought about this aswell, but the surface works completely different than anything else: you have to raise or lower the land, instead of actually pasting a surface element.
The other thing is, that copying and pasting scenery that is placed on sloped surfaces is buggy in general, as there are some issues with how OpenRCT handles that.

I think I will implement it eventually, but maybe it will take a while.

**Comment by Sadret** [comment]
Included in SM v2.0 (to be released soon)

**Comment by guillaumecardon** [comment]
Hello,

In SM 2.0.0, copy paste of surface (slopped or not) doesn't work

- Test with OpenRCT 0.4.1.
- Copy paste a little hill with 9 trees.
- Only trees are pasted
![image](https://user-images.githubusercontent.com/47170797/184544560-9c0425cd-20ab-497a-a071-14d26787af82.png)

**Comment by Sadret** [comment]
Do you have raw paste mode enabled?

**Comment by guillaumecardon** [comment]
You're right, my bad

![image](https://user-images.githubusercontent.com/47170797/184550150-8a49c4b4-b5e6-40a6-8caf-f0d5a4822487.png)

**Comment by Sadret** [comment]
Also, to remove the z-fighting, disable "merge surfaces", which should be off by default.
